language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - export TAP_DIR="$(brew --prefix)/Library/Taps/$TRAVIS_REPO_SLUG"
  - export TAP_NAME=${TRAVIS_REPO_SLUG/'homebrew-'/''}
  - test -z $GIT_URL && (export GIT_URL="https://github.com/$TRAVIS_REPO_SLUG)
  - brew update
  - sudo mkdir -p $TAP_DIR
  - sudo rsync -az "$TRAVIS_BUILD_DIR/" $TAP_DIR/
  - sudo chown -R $USER /usr/local
  - env | grep -E 'TRAVIS_|GIT_'
  - cd $TAP_DIR
  - git reset --hard $TRAVIS_COMMIT
  - git clean -qxdff
  - cd $(brew --prefix)
  - brew tap

script:
#  - brew test-bot --tap=$TAP_NAME --verbose
  - brew test-bot --verbose

notifications:
  email: false
