#!/bin/bash

declare -i is_url
#declare -i is_ssl
declare checksum

if [ -z "$1" ]; then
    echo 'No file or URL specified, exiting.'
    exit 1
fi

if [ `expr "$1" : 'http://'` -gt "0" ] || [ `expr "$1" : 'https://'` -gt "0" ]
then
    is_url=1
else
    is_url=0
fi

if [ "$is_url" = 1 ]; then
    checksum=$(curl -sfkL "$1" | shasum -a 256 -b)
else
    checksum=$(shasum -a 256 -b "$1")
fi

checksum=$(echo "$checksum" | sed 's/ .*//g')

echo "$checksum"
exit 0
