# This is a basic workflow that is manually triggered

name: Homebrew test-bot

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run-test-bot:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set environment
        run: |
          echo "::set-env name=TAP_NAME::${GITHUB_REPOSITORY/'homebrew-'/}"
      - uses: actions/checkout@v2
        with:
          repository: 'yumitsu/homebrew-misc'
      - uses: actions/cache@v2
        with:
          path: |
            - /usr/local/Homebrew
          key: osx-brew-repository
      - name: Update brew
        run: |
          brew update
          brew vendor-gems
          brew install-bundler-gems
      - name: Tap a repo
        run: |
          cd $GITHUB_WORKSPACE
          brew tap
      - name: Run test-bot
        run: |
          brew test-bot --skip-setup --only-formulae --verbose .
